services:
  # A Docker web service
  - type: web
    name: DQ-The-File-Donor
    env: python
    startCommand: python3 bot.py
    buildCommand: pip3 install -U -r requirements.txt
    healthCheckPath: /
    plan: free # optional (defaults to starter)

#End of yaml
